Repository FESI09-Team2/JAMMIT_FE, pull requests merged in 2025-06, with the labels that each got.

#66 [페이지] 모임만들기
  package-lock.json
  src/app/jam/page.tsx
  src/assets/icons/ic_arrowdown.svg
  src/assets/icons/ic_emptyimage.svg
  src/assets/icons/ic_minus.svg
  src/assets/icons/ic_search.svg
  src/components/commons/Dropdown.tsx
  src/components/commons/DropdownMenuList.tsx
  src/components/commons/GroupPageLayout.tsx
  src/components/commons/Input.tsx
  src/components/commons/Modal/ModalEdit.tsx
  src/components/commons/Modal/ModalReview.tsx
  src/components/commons/Textarea.tsx
  src/components/products/group/KakaoMap.tsx
  src/components/products/jam/ImageEdit.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/ModalImgEdit.tsx
  src/components/products/jam/NumberInput.tsx
  src/components/products/jam/SearchInput.tsx
  src/components/products/jam/SessionSelector.tsx
  src/constants/tags.ts
  src/hooks/__tests__/useQueryTab.test.tsx
  src/types/jam.ts
  src/types/kakao.d.ts
  src/types/modal.ts
Labels: 페이지, 리뷰 완료 / 최종 병합

#68 [컴포넌트] 카드 리팩토링
  package-lock.json
  package.json
  src/assets/icons/ic_list_check.svg
  src/components/commons/Card/Footer.tsx
  src/components/commons/Card/TagList.tsx
  src/components/commons/Card/Thumbnail.tsx
  src/components/commons/Card/TitleBlock.tsx
  src/components/commons/Card/index.tsx
  src/components/commons/RecruitCard.tsx
  src/components/commons/RecruitList.tsx
  src/components/products/Recruit/RecruitList.tsx
  src/constants/card.ts
  src/mock/card.mock.ts
  src/styles/globals.css
  src/types/card.ts
  src/utils/getRecruitStatus.ts
Labels: 컴포넌트, 리팩토링

#71 [페이지] 찜하기
  package-lock.json
  src/app/layout.tsx
  src/assets/icons/ic_seleted_arrow.svg
  src/assets/icons/ic_seleted_check.svg
  src/components/commons/Card/Footer.tsx
  src/components/commons/MultiSelectDropdown.tsx
  src/components/products/Recruit/RecruitList.tsx
  src/hooks/.gitkeep
  src/styles/globals.css
Labels: 페이지

#72 [기능] 로그인, 회원가입 api 연결
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/products/login/LoginPage.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
  src/hooks/queries/auth/useLoginMutaion.ts
  src/hooks/queries/user/useSignupMutation.ts
  src/hooks/useRefreshToken.ts
  src/lib/auth/login.ts
  src/lib/auth/signup.ts
  src/lib/axios.ts
  src/lib/react-query.ts
  src/stores/useAuthStore.ts
  src/types/auth.ts
  src/types/user.ts
  src/utils/authApiError.ts
  src/utils/token.ts
Labels: 기능

#75 [페이지] 모임 컴포넌트
  package-lock.json
  package.json
  src/app/mypage/page.tsx
  src/components/commons/Card/Thumbnail.tsx
  src/components/commons/InfinityScroll.tsx
  src/components/products/mypage/Created.tsx
  src/components/products/mypage/Participating.tsx
  src/components/products/mypage/mockCard.ts
  src/hooks/.gitkeep
Labels: 컴포넌트, 기능, 페이지

#77 [컴포넌트] Modal 리팩토링
  src/assets/icons/ic_x.svg
  src/components/commons/Button.tsx
  src/components/commons/Modal/ModalEdit.tsx
  src/components/commons/Modal/ModalInteraction.tsx
  src/components/commons/Modal/ModalReview.tsx
  src/components/commons/Modal/ModalWrapper.tsx
  src/components/commons/TagSection.tsx
  src/components/commons/__tests__/ModalReview.test.tsx
Labels: 컴포넌트, 리팩토링

#80 [컴포넌트] Dropdown 리팩토링
  src/app/jam/page.tsx
  src/components/commons/DatePicker/DatePicker.tsx
  src/components/commons/Dropdown.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/JamPage.tsx
  src/components/products/jam/NumberInput.tsx
  src/components/products/jam/SearchInput.tsx
  src/components/products/jam/SessionSelector.tsx
Labels: 컴포넌트, 리팩토링

#84 [기능] 회원가입 유효성 검사 보완, 이메일 중복 검사 추가
  src/components/products/signup/step1/SignupStep1Page.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
  src/constants/tagsMapping.ts
  src/hooks/queries/user/useUserMeQuery.ts
  src/lib/auth/login.ts
  src/lib/auth/signup.ts
  src/types/tags.ts
Labels: 기능

#85 [페이지] 찜하기 api 연결
  package-lock.json
  package.json
  src/app/wishlist/page.tsx
  src/components/commons/InfinityScroll.tsx
  src/components/commons/RecruitFeed.tsx
  src/components/products/Recruit/RecruitList.tsx
  src/components/products/wish/WishPage.tsx
  src/constants/checkbox.ts
  src/hooks/.gitkeep
  src/lib/wish/wish.ts
  src/styles/globals.css
  src/types/wish.ts
Labels: 페이지

#90 [페이지] 찜하기
  src/app/page.tsx
  src/app/wishlist/page.tsx
  src/app/wishlist/wish.tsx
  src/components/commons/Card/CardItem.tsx
  src/components/commons/Card/Thumbnail.tsx
  src/components/commons/InfinityScroll.tsx
  src/components/commons/Like.tsx
  src/components/commons/RecruitFeed.tsx
  src/components/commons/RecruitHeader.tsx
  src/components/commons/VirtualGrid.tsx
  src/components/products/Recruit/RecruitList.tsx
  src/components/products/mypage/Created.tsx
  src/components/products/mypage/Participating.tsx
  src/components/products/mypage/mockCard.ts
  src/components/products/recruit/RecruitPage.tsx
  src/constants/checkbox.ts
  src/stores/useWishStore.ts
  src/styles/globals.css
  src/types/card.ts
  src/types/wish.ts
  tsconfig.json
Labels: 페이지

#91 [기능] 프로필 카드 수정 api
  package-lock.json
  package.json
  src/components/commons/Modal/ModalEdit.tsx
  src/components/products/mypage/Created.tsx
  src/components/products/mypage/UserCard.tsx
  src/constants/tagsMapping.ts
  src/hooks/.gitkeep
  src/hooks/queries/user/useUpdateProfile.ts
  src/hooks/queries/user/useUpdateProfileImage.ts
  src/lib/mypage/updateprofile.ts
  src/lib/mypage/updateprofileimage.ts
  src/types/modal.ts
  src/types/user.ts
Labels: 기능

#98 [기능] 모임 api
  src/components/commons/InfinityScroll.tsx
  src/components/products/mypage/Created.tsx
  src/components/products/mypage/MyPageContent.tsx
  src/components/products/mypage/Participating.tsx
  src/components/products/mypage/UserCard.tsx
  src/hooks/queries/gather/useGatherMeCreate.ts
  src/hooks/queries/gather/useGatherMeParticipants.ts
  src/lib/gathering/created.ts
  src/lib/gathering/participants.ts
  src/lib/mypage/updateprofile.ts
  src/lib/mypage/updateprofileimage.ts
  src/types/card.ts
  src/types/gather.ts
  src/types/modal.ts
  src/types/tags.ts
  src/types/user.ts
Labels: 기능

#100 [페이지] 모임 상세 페이지 모임 정보 API 연결
  src/components/commons/Card/TagList.tsx
  src/components/commons/GroupPageLayout.tsx
  src/components/commons/InfinityScroll.tsx
  src/components/commons/TagSelector.tsx
  src/components/products/group/GroupInfoSection.tsx
  src/components/products/group/GroupPage.tsx
  src/components/products/group/MemberInfoSection.tsx
  src/components/products/group/MemberList.tsx
  src/components/products/group/MemberRow.tsx
  src/components/products/group/ParticipantsSection.tsx
  src/components/products/group/ParticipationForm.tsx
  src/components/products/group/Typographys.tsx
  src/components/products/mypage/Created.tsx
  src/components/products/mypage/Participating.tsx
  src/hooks/queries/gatherings/useGatheringsDetailQuery.ts
  src/hooks/queries/gatherings/useGatheringsParticipantsQuery.ts
  src/hooks/useQueryTab.tsx
  src/lib/gatherings/gatherings.ts
  src/types/gathering.ts
  src/types/tags.ts
  src/utils/formatDate.ts
Labels: 기능, 페이지

#106 [기능] UserCard zustand 적용
  src/components/products/mypage/MyPageContent.tsx
  src/components/products/mypage/UserCard.tsx
  src/components/products/mypage/gather/Created.tsx
  src/components/products/mypage/gather/Participating.tsx
  src/types/card.ts
Labels: 기능

#105 [페이지] 작성가능한리뷰
  src/app/jam/page.tsx
  src/app/mypage/page.tsx
  src/components/commons/Card/CardItem.tsx
  src/components/commons/Card/Footer.tsx
  src/components/products/mypage/MyPageContent.tsx
  src/components/products/mypage/ReviewsToWrite.tsx
  src/components/products/mypage/gather/Created.tsx
  src/components/products/mypage/gather/Participating.tsx
  src/components/products/mypage/review/ReviewList.tsx
  src/components/products/mypage/review/ReviewStatus.tsx
  src/components/products/mypage/review/ReviewsReceived.tsx
  src/components/products/mypage/towrite/ReviewsToWrite.tsx
  src/components/products/recruit/RecruitPage.tsx
  src/constants/checkbox.ts
  src/hooks/queries/review/useReviewInfiniteQuery.ts
  src/hooks/queries/review/useSuspenseReview.ts
  src/lib/review/towrite.ts
  src/lib/wish/wish.ts
  src/stores/useWishStore.ts
  src/types/card.ts
  src/types/review.ts
  src/types/tags.ts
  src/types/wish.ts
Labels: 페이지

#112 [기능] 완료된 모임 리뷰 작성 기능
  src/components/commons/Modal/ModalReview.tsx
  src/components/commons/__tests__/ModalReview.test.tsx
  src/components/products/group/GroupInfoSection.tsx
  src/components/products/group/GroupPage.tsx
  src/components/products/group/ParticipantsSection.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
  src/constants/review.ts
  src/hooks/queries/review/usePostReviewMutation.ts
  src/lib/review/review.ts
  src/types/review.ts
Labels: 기능

#111 [기능] 리뷰 api 다시
  src/app/page.tsx
  src/app/wishlist/page.tsx
  src/assets/icons/ic_sort.svg
  src/assets/images/img_main_banner.jpg
  src/assets/images/index.ts
  src/components/commons/Card/TagList.tsx
  src/components/commons/Card/Thumbnail.tsx
  src/components/commons/InfinityScroll.tsx
  src/components/commons/MultiSelectDropdown.tsx
  src/components/commons/RecruitHeader.tsx
  src/components/products/mypage/MyPageContent.tsx
  src/components/products/mypage/review/ReviewList.tsx
  src/components/products/mypage/review/ReviewsReceived.tsx
  src/components/products/mypage/towrite/ReviewsToWrite.tsx
  src/components/products/recruit/RecruitPage.tsx
  src/constants/checkbox.ts
  src/constants/review.ts
  src/hooks/queries/recruit/useRecruit.ts
  src/hooks/queries/review/useReviewInfiniteQuery.ts
  src/hooks/queries/review/useSuspenseReview.ts
  src/lib/recruit/recruit.ts
  src/lib/review/received.ts
  src/lib/review/towrite.ts
  src/types/card.ts
  src/types/recruit.ts
  src/types/review.ts
  src/utils/imgChange.ts
Labels: 기능 개선, 기능, 리팩토링

#117 [버그] 모임 상세 비로그인시 참여멤버 탭만 접근 못하게 수정
  src/components/products/group/GroupPage.tsx
  src/hooks/queries/gatherings/useApproveParticipantMutation.ts
  src/hooks/queries/gatherings/useDeleteGatheringMutation.ts
  src/hooks/queries/gatherings/useGatheringsParticipantsQuery.ts
Labels: 버그

#120 [컴포넌트, 페이지] 모임 만들기 - 이미지 수정 모달 더보기 기능
  src/assets/images/img_banner_01.jpg
  src/assets/images/img_banner_01.png
  src/assets/images/img_banner_02.jpg
  src/assets/images/img_banner_02.png
  src/assets/images/img_banner_03.jpg
  src/assets/images/img_banner_03.png
  src/assets/images/img_banner_04.jpg
  src/assets/images/img_banner_04.png
  src/assets/images/img_banner_05.jpg
  src/assets/images/img_banner_05.png
  src/assets/images/img_banner_06.jpg
  src/assets/images/img_banner_06.png
  src/assets/images/img_banner_07.jpg
  src/assets/images/img_banner_07.png
  src/assets/images/img_banner_08.jpg
  src/assets/images/img_banner_08.png
  src/assets/images/img_banner_09.jpg
  src/assets/images/img_banner_09.png
  src/assets/images/img_banner_10.jpg
  src/assets/images/img_banner_10.png
  src/assets/images/img_banner_11.jpg
  src/assets/images/img_banner_11.png
  src/assets/images/img_banner_12.jpg
  src/assets/images/img_banner_12.png
  src/assets/images/img_banner_13.png
  src/assets/images/img_banner_14.png
  src/assets/images/img_banner_15.png
  src/assets/images/img_banner_16.png
  src/assets/images/img_banner_17.png
  src/assets/images/img_banner_18.png
  src/assets/images/index.ts
  src/components/products/jam/ModalImgEdit.tsx
  src/constants/bannerImages.ts
  src/utils/imgChange.ts
Labels: 컴포넌트, 페이지

#124 [기능] 모임 상세 페이지 좋아요, 공유 기능
  src/app/wishlist/page.tsx
  src/assets/icons/ic_share.svg
  src/assets/images/img_character01.png
  src/components/products/group/GroupInfoSection.tsx
  src/components/products/group/ShareLinkModal.tsx
Labels: 기능

#136 [페이지] 모임 만들기 페이지 모달 적용
  src/app/page.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/JamPage.tsx
  src/components/products/recruit/RecruitPage.tsx
  src/hooks/queries/gather/useGatherRegister.ts
  src/types/recruit.ts
Labels: 페이지

#138 [리팩토링] 마이페이지, 모임생성페이지, 라이트하우스 점수향상
  src/app/layout.tsx
  src/app/page.tsx
  src/components/commons/Card/TitleBlock.tsx
  src/components/commons/Gnb.tsx
  src/components/products/jam/DateFormSection.tsx
  src/components/products/jam/DescriptionFormSection.tsx
  src/components/products/jam/GenreFormSection.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/SessionFormSection.tsx
  src/components/products/mypage/UserCard.tsx
  src/hooks/queries/gather/useGatherMeCreate.ts
  src/hooks/queries/gather/useGatherMeParticipants.ts
  src/hooks/queries/gather/useGatherModify.ts
  src/hooks/queries/gather/useGatherRegister.ts
  src/hooks/useQueryTab.tsx
  src/lib/react-query.ts
  src/styles/globals.css
  src/utils/authApiError.ts
Labels: 리팩토링

#139 [기능] 리뷰 작성 완료한 참여자 리뷰작성 버튼 비활성화
  src/components/commons/Modal/ErrorModal.tsx
  src/components/products/group/GroupInfoSection.tsx
  src/components/products/group/GroupPage.tsx
  src/components/products/group/MemberInfoSection.tsx
  src/components/products/group/ParticipantsSection.tsx
  src/hooks/__tests__/useQueryTab.test.tsx
  src/hooks/queries/review/usePostReviewMutation.ts
  src/hooks/queries/review/useWrittenReviewsQuery.ts
  src/hooks/useQueryTab.tsx
  src/lib/review/written.ts
  src/stores/useUserStore.ts
  src/utils/authService.ts
Labels: 버그, 기능

#143 [기능] 사진 업로드 용량 제한 설정
  src/components/commons/Modal/ModalEdit.tsx
  src/components/commons/Modal/ModalWrapper.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
  src/hooks/useImageUpload.ts
Labels: 기능

#148 [레이아웃] 모임상세, 로그인, 회원가입, GNB 반응형 적용
  src/assets/icons/ic_jammit_logo.svg
  src/components/commons/AuthCard.tsx
  src/components/commons/Gnb.tsx
  src/components/commons/GroupPageLayout.tsx
  src/components/products/group/GroupInfoSection.tsx
  src/components/products/group/GroupPage.tsx
  src/components/products/group/MemberList.tsx
  src/components/products/group/ParticipantsSection.tsx
  src/components/products/group/ParticipationForm.tsx
  src/components/products/login/LoginPage.tsx
  src/components/products/signup/step1/SignupStep1Page.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
Labels: 레이아웃

#152 [기능] sentry
  .gitignore
  next.config.ts
  package-lock.json
  package.json
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/api/sentry-example-api/route.ts
  src/app/global-error.tsx
  src/app/sentry-example-page/page.tsx
  src/components/products/group/GroupPage.tsx
  src/components/products/group/ParticipantsSection.tsx
  src/components/products/login/LoginPage.tsx
  src/components/products/mypage/UserCard.tsx
  src/components/products/mypage/gather/ParticipatingList.tsx
  src/components/products/mypage/review/ReviewList.tsx
  src/components/products/mypage/towrite/ReviewsToWrite.tsx
  src/components/products/recruit/RecruitPage.tsx
  src/components/products/signup/step1/SignupStep1Page.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
  src/hooks/queries/gather/useGatherModify.ts
  src/hooks/queries/gather/useGatherRegister.ts
  src/hooks/queries/gatherings/useApproveParticipantMutation.ts
  src/hooks/queries/gatherings/useCancelParticipateGathering.ts
  src/hooks/queries/gatherings/useDeleteGatheringMutation.ts
  src/hooks/queries/gatherings/useParticipateGatheringsMutation.ts
  src/hooks/queries/gatherings/useRejectParticipantMutation.ts
  src/hooks/useImageUpload.ts
  src/instrumentation-client.ts
  src/instrumentation.ts
  src/utils/authApiError.ts
  src/utils/useSentryErrorLogger.ts
Labels: 기능

#155 [리팩토링] 메인 api 변경
  src/app/page.tsx
  src/components/products/recruit/RecruitPage.tsx
  src/hooks/queries/recruit/useRecruit.ts
  src/lib/recruit/recruit.ts
Labels: 리팩토링

#158 [기능] 주최자에 대한 리뷰 작성 기능
  src/components/products/group/GroupPage.tsx
  src/components/products/group/GroupPageSkeleton.tsx
  src/components/products/group/MemberInfoSection.tsx
  src/components/products/group/MemberList.tsx
  src/components/products/group/MemberRow.tsx
  src/components/products/group/ParticipantsSection.tsx
  src/styles/utililtes.css
Labels: 기능

#162 [리팩토링] 리뷰
  src/app/group/[groupId]/reviews/[member]/page.tsx
  src/app/video/page.tsx
  src/app/wishlist/page.tsx
  src/components/commons/Card/CardItem.tsx
  src/components/commons/Card/Footer.tsx
  src/components/commons/InfinityScroll.tsx
  src/components/commons/VirtualGrid.tsx
  src/components/products/group/MemberInfoSection.tsx
  src/components/products/group/MemberList.tsx
  src/components/products/group/MemberRow.tsx
  src/components/products/group/ReviewPageClient.tsx
  src/components/products/mypage/MyPageContent.tsx
  src/components/products/mypage/UserCard.tsx
  src/components/products/mypage/UserCardItem.tsx
  src/components/products/mypage/review/ReviewItems.tsx
  src/components/products/mypage/review/ReviewList.tsx
  src/components/products/mypage/review/ReviewStatus.tsx
  src/components/products/mypage/review/ReviewsReceived.tsx
  src/components/products/mypage/towrite/ReviewsToWrite.tsx
  src/components/products/wish/VirtualGrid.tsx
  src/hooks/queries/review/usePrefetchReview.ts
  src/hooks/queries/review/useReviewInfiniteQuery.ts
  src/hooks/queries/review/useSuspenseReview.ts
  src/lib/review/reviewRead.ts
  src/lib/review/towrite.ts
  src/types/card.ts
  src/types/review.ts
Labels: 리팩토링

#164 [리팩토링] 모임생성/수정 페이지
  src/components/commons/Dropdown.tsx
  src/components/commons/Modal/ModalReview.tsx
  src/components/commons/Textarea.tsx
  src/components/commons/__tests__/TextArea.test.tsx
  src/components/products/group/ParticipationForm.tsx
  src/components/products/jam/DescriptionFormSection.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/JamPage.tsx
  src/components/products/jam/NumberInput.tsx
  src/components/products/jam/SessionFormSection.tsx
  src/components/products/jam/SessionSelector.tsx
Labels: 리팩토링

#167 [버그] textarea 변경후 formprovider 적용미흡
  src/components/products/group/ParticipationForm.tsx
Labels: 버그

#179 [기능] 영상 기능 전용 api client 추가
  src/utils/apiClient.ts
Labels: 기능

#177 [리팩토링] 쿼리키 계층화
  src/app/page.tsx
  src/components/products/jam/JamPage.tsx
  src/components/products/mypage/MyPageContent.tsx
  src/components/products/mypage/review/ReviewList.tsx
  src/components/products/mypage/review/ReviewStatus.tsx
  src/components/products/mypage/towrite/ReviewsToWrite.tsx
  src/components/products/recruit/RecruitPage.tsx
  src/hooks/queries/gather/useGatherMeCreate.ts
  src/hooks/queries/gather/useGatherMeParticipants.ts
  src/hooks/queries/gatherings/useApproveParticipantMutation.ts
  src/hooks/queries/gatherings/useCancelParticipateGathering.ts
  src/hooks/queries/gatherings/useDeleteGatheringMutation.ts
  src/hooks/queries/gatherings/useGatheringsDetailQuery.ts
  src/hooks/queries/gatherings/useGatheringsParticipantsQuery.ts
  src/hooks/queries/gatherings/useParticipateGatheringsMutation.ts
  src/hooks/queries/gatherings/useRejectParticipantMutation.ts
  src/hooks/queries/queryKeys.ts
  src/hooks/queries/recruit/useRecruit.ts
  src/hooks/queries/review/usePostReviewMutation.ts
  src/hooks/queries/review/usePrefetchReview.ts
  src/hooks/queries/review/useReviewInfiniteQuery.ts
  src/hooks/queries/review/useWrittenReviewsQuery.ts
  src/hooks/queries/user/useUpdateProfile.ts
  src/hooks/queries/user/useUpdateProfileImage.ts
  src/hooks/queries/user/useUserMeQuery.ts
  src/utils/authService.ts
Labels: 기능 개선, 리팩토링

#181 [레이아웃] 모임 생성/수정 페이지 반응형
  src/assets/icons/ic_search.svg
  src/components/commons/DatePicker/DatePicker.tsx
  src/components/commons/Dropdown.tsx
  src/components/commons/DropdownMenuList.tsx
  src/components/commons/Input.tsx
  src/components/commons/Modal/ModalWrapper.tsx
  src/components/products/jam/DateFormSection.tsx
  src/components/products/jam/ImageEdit.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/JamPage.tsx
  src/components/products/jam/ModalImgEdit.tsx
  src/components/products/jam/SearchInput.tsx
  src/components/products/jam/SessionFormSection.tsx
  src/components/products/jam/SessionSelector.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
  src/hooks/usePreventScroll.ts
Labels: 레이아웃

#182 [페이지] 비디오 리스트 페이지
  next.config.ts
  public/images/main/img_video_banner.avif
  src/app/videos/page.tsx
  src/components/commons/Gnb.tsx
  src/components/commons/InfinityScroll.tsx
  src/components/products/videos/VideoCard.tsx
  src/components/products/videos/VideoList.tsx
  src/components/products/videos/VideoListBanner.tsx
  src/components/products/videos/VideoListControBar.tsx
  src/hooks/queries/video/useVideoInfiniteQuery.ts
  src/lib/video/video.ts
  src/types/video.ts
  src/utils/formatDate.ts
Labels: 페이지

#186 [페이지] 마이페이지 내가 올린 영상 목록
  src/components/products/group/MemberList.tsx
  src/components/products/group/MemberRow.tsx
  src/components/products/mypage/MyPageContent.tsx
  src/components/products/mypage/video/MyVideo.tsx
  src/components/products/videos/VideoCard.tsx
  src/components/products/videos/VideoCardSkeleton.tsx
  src/components/products/videos/VideoListControBar.tsx
  src/hooks/queries/gather/usePrefetchedCoint.ts
  src/hooks/queries/queryKeys.ts
  src/hooks/queries/video/useUserVideoCountQuery.ts
  src/hooks/queries/video/useUserVideoInfiniteQuery.ts
  src/lib/video/video.ts
  src/types/video.ts
Labels: 페이지

#191 [컴포넌트] input
  src/components/commons/Input.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/SessionFormSection.tsx
Labels: 컴포넌트

#189 [페이지] 사용자가 올린 영상 리스트
  public/images/main/img_video_banner_pc.avif
  public/images/main/img_video_banner_tab.avif
  src/components/commons/Gnb.tsx
  src/components/products/group/MemberList.tsx
  src/components/products/group/MemberRow.tsx
  src/components/products/group/ParticipantsSection.tsx
  src/components/products/group/ReviewPageClient.tsx
  src/components/products/mypage/UserCardItem.tsx
  src/components/products/mypage/review/ReviewItems.tsx
  src/components/products/mypage/video/MyVideo.tsx
  src/components/products/videos/VideoCard.tsx
  src/components/products/videos/VideoList.tsx
  src/components/products/videos/VideoListBanner.tsx
  src/components/products/videos/VideoListControBar.tsx
  src/hooks/queries/gather/usePrefetchedCoint.ts
  src/hooks/queries/review/usePrefetchReview.ts
  src/types/gathering.ts
  src/types/review.ts
Labels: 페이지

#187 [페이지] 영상업로드
  package-lock.json
  package.json
  public/json/jump.json
  src/app/api/sentry-example-api/route.ts
  src/app/video/[videoId]/page.tsx
  src/app/video/upload/page.tsx
  src/assets/icons/ic_video.svg
  src/components/commons/Input.tsx
  src/components/commons/Textarea.tsx
  src/components/products/group/ParticipantsSection.tsx
  src/components/products/login/LoginPage.tsx
  src/components/products/mypage/UserCard.tsx
  src/components/products/mypage/review/ReviewItems.tsx
  src/components/products/recruit/RecruitPage.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
  src/components/products/video/VideoDetailClient.tsx
  src/components/products/videos/VideoCard.tsx
  src/hooks/queries/auth/useSendCodeMutation.ts
  src/hooks/queries/gather/useGatherModify.ts
  src/hooks/queries/gather/useGatherRegister.ts
  src/hooks/queries/gatherings/useApproveParticipantMutation.ts
  src/hooks/queries/gatherings/useCancelParticipateGathering.ts
  src/hooks/queries/gatherings/useDeleteGatheringMutation.ts
  src/hooks/queries/gatherings/useParticipateGatheringsMutation.ts
  src/hooks/queries/gatherings/useRejectParticipantMutation.ts
  src/hooks/queries/video/useVideoDetail.ts
  src/hooks/queries/video/useVideoUpload.ts
  src/hooks/useImageUpload.ts
  src/hooks/useRefreshToken.ts
  src/lib/video/videoUpload.ts
  src/types/video.ts
  src/utils/authApiError.ts
  src/utils/date.ts
  src/utils/logToSentry.ts
Labels: 페이지

#192 [페이지] 업로드
  src/app/video/page.tsx
  src/app/video/upload/page.tsx
  src/app/wishlist/page.tsx
  src/components/commons/Gnb.tsx
  src/components/commons/GoGether.tsx
  src/components/products/mypage/SkeletonUserCard.tsx
  src/components/products/mypage/review/ReviewItems.tsx
  src/components/products/mypage/review/SkeletonReviewList.tsx
  src/components/products/mypage/review/SkeletonStatus.tsx
  src/components/products/video/VideoDetailClient.tsx
  src/components/products/video/VideoDetailSkeleton.tsx
  src/hooks/queries/queryKeys.ts
  src/hooks/queries/video/useVideoDetail.ts
  src/hooks/queries/video/useVideoUpload.ts
  src/lib/video/videoUpload.ts
  src/types/video.ts
Labels: 버그

#196 [QA] 담당페이지수정
  src/components/commons/DatePicker/DatePicker.tsx
  src/components/commons/DropdownMenuList.tsx
  src/components/commons/Input.tsx
  src/components/commons/Modal/ModalReview.tsx
  src/components/products/jam/ModalImgEdit.tsx
  src/components/products/jam/SessionFormSection.tsx
  src/components/ui/calendar.tsx
Labels: 버그

#199 [QA] qa....
  src/app/video/[videoId]/page.tsx
  src/components/commons/Modal/ModalEdit.tsx
  src/components/commons/RecruitHeader.tsx
  src/components/commons/Textarea.tsx
  src/components/products/mypage/review/SkeletonReviewList.tsx
  src/components/products/recruit/RecruitPage.tsx
  src/components/products/signup/step1/SignupStep1Page.tsx
  src/components/products/video/VideoDetailClient.tsx
  src/components/products/videos/VideoListBanner.tsx
  src/hooks/queries/video/useVideoUpload.ts
  src/styles/globals.css
Labels: 버그

#200 [QA] 로그인시 아이디 저장 기능
  src/app/mypage/page.tsx
  src/components/products/group/MemberRow.tsx
  src/components/products/login/LoginPage.tsx
  src/components/products/video/VideoDetailClient.tsx
Labels: 기능

#202 [QA] 좋아요페이지 초기화
  src/app/global-error.tsx
  src/app/wishlist/page.tsx
  src/components/products/video/VideoDetailClient.tsx
Labels: 버그

#203 [QA] 담당페이지수정
  src/components/products/jam/GenreFormSection.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/JamPage.tsx
  src/components/products/jam/SessionFormSection.tsx
Labels: 버그
