Repository FESI09-Team2/JAMMIT_FE, pull requests merged in 2025-05, with the labels that each got.

#5 [컴포넌트] Input - text
  package-lock.json
  package.json
  src/app/testpage/.gitkeep
  src/app/testpage/input/page.tsx
  src/components/commons/Input.tsx
  src/components/commons/input.tsx
Labels: 컴포넌트

#6 [컴포넌트] Gnb
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/wishlist/page.tsx
  src/assets/icons/ic_default_profile.svg
  src/components/commons/.gitkeep
  src/components/commons/Gnb.tsx
  src/components/commons/__tests__/Gnb.test.tsx
Labels: 컴포넌트, 레이아웃

#8 [컴포넌트] Input - password
  package-lock.json
  package.json
  src/app/testpage/input/page.tsx
  src/components/commons/Input.tsx
  src/components/commons/__tests__/Input.test.tsx
  tsconfig.json
Labels: 컴포넌트

#18 [컴포넌트] Button
  package-lock.json
  package.json
  src/app/testpage/button/page.tsx
  src/components/commons/Button.tsx
  src/components/commons/__tests__/Button.test.tsx
Labels: 컴포넌트

#24 [컴포넌트] Modal - Interaction
  src/app/testpage/modal/page.tsx
  src/components/commons/ModalInteraction.tsx
  src/components/commons/ModalWarraper.tsx
  src/components/commons/ModalWrapper.tsx
  src/components/commons/__tests__/InteractionModal.test.tsx
  src/components/commons/__tests__/ModalWrapper.test.tsx
Labels: 컴포넌트

#27 [컴포넌트] Modal - review
  package-lock.json
  package.json
  src/app/testpage/modal/page.tsx
  src/assets/icons/ic_emptyheart.svg
  src/assets/icons/ic_fillheart.svg
  src/components/commons/HeartRating.tsx
  src/components/commons/ModalInteraction.tsx
  src/components/commons/ModalReview.tsx
  src/components/commons/ModalWarraper.tsx
  src/components/commons/ModalWrapper.tsx
  src/components/commons/__tests__/ModalInteraction.test.tsx
  src/components/commons/__tests__/ModalReview.test.tsx
Labels: 컴포넌트

#31 [페이지] 로그인, 회원가입 페이지 디자인 적용
  src/app/login/login.test.tsx
  src/app/login/page.tsx
  src/app/signup/step1/page.tsx
  src/app/signup/step1/step1.test.tsx
  src/components/commons/AuthCard.tsx
  src/components/commons/Layout.tsx
  src/components/products/login/LoginPage.tsx
  src/components/products/signup/step1/SignupStep1Page.tsx
Labels: 페이지, 스타일

#34 [컴포넌트] Modal - jam
  src/app/testpage/modal/page.tsx
  src/components/commons/ModalReview.tsx
  src/components/commons/ModalZam.tsx
Labels: 컴포넌트

#33 [컴포넌트] 태그 선택 컴포넌트
  src/app/testpage/tag-selector/page.tsx
  src/assets/icons/ic_check.svg
  src/assets/icons/ic_plus.svg
  src/components/commons/TagSelector.tsx
  src/components/commons/__tests__/TagSelector.test.tsx
Labels: 컴포넌트

#30 [컴포넌트] Card
  package-lock.json
  src/components/commons/RecruitList.tsx
  src/components/products/Recruit/RecruitList.tsx
  src/styles/globals.css
  src/types/types.ts
Labels: 컴포넌트

#50 [페이지] 모임 상세 페이지 기본 UI
  src/app/group/[groupId]/page.tsx
  src/app/layout.tsx
  src/assets/images/img_banner_01.jpg
  src/assets/images/img_banner_02.jpg
  src/assets/images/img_banner_03.jpg
  src/assets/images/img_banner_04.jpg
  src/assets/images/img_banner_05.jpg
  src/assets/images/img_banner_06.jpg
  src/assets/images/img_banner_07.jpg
  src/assets/images/img_banner_08.jpg
  src/assets/images/img_banner_09.jpg
  src/assets/images/img_banner_10.jpg
  src/assets/images/img_banner_11.jpg
  src/assets/images/img_banner_12.jpg
  src/components/commons/GroupPageLayout.tsx
  src/components/products/group/GroupInfoSection.tsx
  src/components/products/group/GroupPage.tsx
  src/constants/bannerImages.ts
  src/constants/tags.ts
  src/styles/globals.css
  src/styles/utililtes.css
Labels: 컴포넌트, 페이지

#54 [페이지] 로그인, 회원가입 페이지
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/login/login.test.tsx
  src/app/login/page.tsx
  src/app/signup/step1/page.tsx
  src/app/signup/step1/step1.test.tsx
  src/app/signup/step2/page.tsx
  src/app/signup/step2/step2.test.tsx
  src/components/commons/AuthCard.tsx
  src/components/commons/Button.tsx
  src/components/commons/Gnb.tsx
  src/components/commons/Input.tsx
  src/components/commons/Layout.tsx
  src/components/products/login/LoginPage.tsx
  src/components/products/signup/step1/SignupStep1Page.tsx
  src/components/products/signup/step2/SignupStep2Page.tsx
  src/stores/useSignupStore.ts
Labels: 리뷰 완료 / 최종 병합

#63 [컴포넌트]: date-picker 버전 업그레이드에 따른 커스텀 수정
  src/components/commons/DatePicker/DatePicker.tsx
  src/components/ui/calendar.tsx
Labels: 컴포넌트

#64 [페이지] 이미지변경 폼 컴포넌트
  components.json
  package-lock.json
  package.json
  src/app/jam/page.tsx
  src/app/testpage/date-picker/page.tsx
  src/assets/icons/ic_arrow_left.svg
  src/assets/icons/ic_arrow_right.svg
  src/assets/icons/ic_calendar.svg
  src/components/commons/DatePicker/DatePicker.tsx
  src/components/commons/DatePicker/TimePicker.tsx
  src/components/products/jam/ImageEdit.tsx
  src/components/products/jam/JamFormSection.tsx
  src/components/products/jam/ModalImgEdit.tsx
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  src/lib/utils.ts
  src/styles/globals.css
Labels: 컴포넌트, 페이지
